management:
  endpoints:
    web:
      exposure:
        include: "*"
spring-console:
  monitor:
    poll-interval: "500ms"
    compare-scale: 3


logging:
  level:
    root: INFO
    org.kasource.spring.console.value: DEBUG
    org.kasource.spring.console.monitor: DEBUG
